### ISSUE TITLE
Disposition is treated as attachment when it's specified as inline

### ISSUE THREAD

**Issue by yurikuzn** [php-mime-mail-parser/php-mime-mail-parser#125]
Code that changes disposition: https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/master/src/Parser.php#L409

Case:
```
Content-Type: image/png; name="=?UTF-8?B?aW1hZ2UwMDEucG5n?="
Content-Disposition: inline
Content-ID: <image001.png@01D22EA3.4D89F740>
Content-Transfer-Encoding: base64
```

**Comment by eXorus** [comment]
Hello,

What is the result expected for you ? If there is a name you will show the image like an attachment and inline.
Because name for inline doesn't mean anything.

**Comment by yurikuzn** [comment]
Hi,

This part is `inline` attachment and supposed to be displayed in the body of email. But when I get disposition with getContentDisposition method it return `attachment` because of indicated code line I mentioned above. Is it properly to treat the part as an `attachment` even if `inline` is specified?

Thanks

**Comment by eXorus** [comment]
I understand and I know it's bad :) to do like this but RFC 2183 is a poor standard so I need to catch more attachment sometimes.

Why do you need to use getContentDisposition() ? you can print email with getMessageBody('htmlEmbedded').

**Comment by yurikuzn** [comment]
We store attachments separately as a files in our application. It's already implemented w/ another library (Zend/Mail) but that is very buggy so we are looking for more robust solution. 

We store html body in database for search purpose and wouldn't like to have attachments be there.

**Comment by eXorus** [comment]
OK I understand but I don't know what to do.

Html body can be saved without attachment with getMessageBody('html')

saveAttachments() and getAttachments() will treat inline and attachment. And it's a choice because some people want that.

Maybe the only solution is to purpose to you a getAttachments that return the attachments with the real content-disposition and not only the content-disposition calculated.

```php
if (count($attachments) > 0) {
    foreach ($attachments as $attachment) {
        if ($attachment->realContentDisposition != 'inline') {
                //do what you want
        }
    }
}
```

**Comment by yurikuzn** [comment]
Actually it's not a problem since I've already have overriden the method to make it work as we need. Thank you very much.

**Comment by eXorus** [comment]
I keep it because it's a good point to improve in the next version.

**Comment by leeoniya** [comment]
Ran into something similar today from some craigslist emails. Both of these get saved as `noname*` files:

```
------------=_1478412575-11078-22
Content-Type: text/plain
Content-Disposition: inline
Content-Transfer-Encoding: 7bit
MIME-Version: 1.0
X-Mailer: MIME-tools 5.502 (Entity 5.502)

------------=_1478412575-11078-22
Content-Type: text/html
Content-Disposition: inline
Content-Transfer-Encoding: 7bit
MIME-Version: 1.0
X-Mailer: MIME-tools 5.502 (Entity 5.502)
```

Another thing that could be at least helpful is having the parser validated that the file extension written to disk matches the `Content-Type` rather than being absent and having to open notepad to figure out what it is. This also happens is buggy programs provide a filename without an extension (had this happen on Android..correct content-type and filename without extension).

I would suggest that both `getAttachments` and `saveAttachments` get an extra parameter or two that allow the user to exclude `inline` (especially non-encoded) and also to enforce file extensions for common content-types.

**Comment by eXorus** [comment]
As you can see I have not much time now.

I appreciate your comment and I would look one day. If you have time you can send me a PR.

**Comment by fko2221** [comment]
I don't understand why you check for `isset($filename) === true` on line 420. On line 404 you set `$filename = 'noname'` so isset($filename) will always evaluate to true.

**Comment by eXorus** [comment]
Maybe because this is stupid :)
I think it can be removed.

**Comment by eXorus** [comment]
@yurikuzn We don't change the Content-Disposition anymore.
I added a test to be sure.

@leeoniya I don't have the full raw email so I can't reproduce, but it looks normal. If you save an inline attachment that don't have name I will create one.
About the extension validation I created a new issue #312 
About your suggestion, it's already done for getAttachments/saveAttachments you can filter with different filters or boolean. I will improve the code in the next major version with the #311
