### ISSUE TITLE
Attachement should extends \SplFileInfo

### ISSUE THREAD

**Issue by kcassam** [php-mime-mail-parser/php-mime-mail-parser#136]
Attachement class should extends \SplFileInfo, it would be easier to work with in existing code (same interface) and it will be lighter

http://php.net/manual/en/class.splfileinfo.php

for example, no need to redefine getFilename function http://php.net/manual/en/splfileinfo.getfilename.php

I could code it if there is a chance that my PR be accepted, so do you agree ?

**Comment by eXorus** [comment]
It can be a good solution, but getFileName need to work also to protect existing user.

SplFileInfo is in the core of PHP, no need to add another extension ?

**Comment by kcassam** [comment]
Sorry I did not see your comment.

I don't understand : "getFileName need to work also to protect existing user". Can you explain ?

SplFileInfo does not need any extension

**Comment by eXorus** [comment]
I don't understand why I write this :)
I was asking to keep the same actual interface without breaking changes.

If there is breaking changes it will be the next version 3.0 that I want since a long time but I need to rewrite everything from scratch.

**Comment by kcassam** [comment]
I fully agree with no breaking changes for this version. When I have time, I'll make a PR

**Comment by eXorus** [comment]
No PR done, but I'm tried to do it.

It works but not very useful because most of the time the file is not saved it's just a representation.
So it's nice to:
- remove the getFilename
- be able to do getBasename
- be able to do getExtension


Must all the others functions will not work because the file doesn't exist (no path).

I think I will close the PR and this issue.
