### ISSUE TITLE
Composer issue.

### ISSUE THREAD

**Issue by Okdesk** [php-mime-mail-parser/php-mime-mail-parser#146]
I ran into the exception "proc_get_status() has been disabled for security reasons", and I am not able to fix it, after doing research on Google. Refer to issue #144. I am opening a new issue because #144 was closed.

Could you tell me how to fix it?

**Comment by eXorus** [comment]
Hello,

I don't think it's related to php-mime-mail-parser because I don't use Symfony/Component. I think your issue is related to composer or your environment.

Try to update composer: composer self-update
or 
- Remove the proc_get_status string from the disable_functions at php.ini* file
- Ask your hosting provider to remove the string above if you don't have an access to the php.ini* file
- Change hosting provider which allows the running of the proc_get_status function.
