### ISSUE TITLE
What /vendor/autoload.php ? 

### ISSUE THREAD

**Issue by adrianTNT** [php-mime-mail-parser/php-mime-mail-parser#208]
Hello.
I downloaded the zip and I was expecting to be able to include a php file from the zip, but the readme says 

`require_once __DIR__.'/vendor/autoload.php';`

What autoload.php is that ?

**Comment by eXorus** [comment]
Hello,

All PHP packages are now using composer and you should also use it because it's a great tool to manage you dependencies.

`composer require php-mime-mail-parser/php-mime-mail-parser`
https://getcomposer.org/

overwise you can copy all the files in a folder and require each file you need and first of all src/Parser.php
