### ISSUE TITLE
save individual attachments

### ISSUE THREAD

**Issue by marcin11** [php-mime-mail-parser/php-mime-mail-parser#263]
This is my code, very simple
$attachments = $parser->getAttachments(false);
foreach ($attachments as $attachment) {
    echo 'Filename : '.$attachment->getFilename().'\n';
    echo "Path : ".$attachment->save('/tmp/', Parser::ATTACHMENT_DUPLICATE_SUFFIX)."\n";
    }
Saving all attachment with $parser->saveAttachments('/path/to/save/attachments/'); work just fine,
But when in loop I get this error:
PHP Fatal error:  Call to undefined method PhpMimeMailParser\Attachment::save()
save is working in your source when saving all attachments
What am I doing wrong?

Also :Parser::ATTACHMENT_DUPLICATE_SUFFIX does not generate logo.jpg, logo_1.jpg, ..., logo_100.jpg
It generates logo.jpg, logo.jpg8bv1tw ..., logo.jpgbqij2y
Also ATTACHMENT_RANDOM_FILENAME does not preserve the extensions, it generates random file name without extension aO5PF2 fzZrsRy

**Comment by eXorus** [comment]
Hello,

Could you provide me the version you are using and the full code because it's working well in my test on master:
https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/b5a2e7672801f1f142a91924be9302714a5c06dd/tests/AttachmentTest.php#L42

As you can see here also https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/b5a2e7672801f1f142a91924be9302714a5c06dd/tests/AttachmentTest.php#L103-L109
the ATTACHMENT_DUPLICATE_SUFFIX strategy works fine. If your email has only one attachment logo.jpg and you save the attachment multiple times it will create logo.jpg and logo_1.jpg until a maxDuplicateNumber and after a random file with the extension.

For ATTACHMENT_RANDOM_FILENAME that's true that it not preserve the extensions. I will fix that it's a bug.

**Comment by marcin11** [comment]
This one is on me, I had an older php version installed, after upgrade, saving individual files worked as well as DUPLICATE_SUFFIX, but as you pointed out RANDOM_FILENAME does not preserves the extensions.
Thank you for your quick replay.

**Comment by eXorus** [comment]
Fixed in 5.0.5

Thanks a lot for the report
