### ISSUE TITLE
Add check if decoded text is really UTF-8

### ISSUE THREAD

**Issue by ThomasLandauer** [php-mime-mail-parser/php-mime-mail-parser#329]
```
Content-Type: text/plain
Content-Transfer-Encoding: quoted-printable

f=FCr m=F6glich h=E4ufig
```
The encoding is Windows-1252, but that's not declared anywhere (neither in any header, nor in this MIME part). `$parser->getMessageBody('text')` returns:
```
f�r m�glich h�ufig
```
And if I try to persist this to the database with Doctrine, I'm getting:

> [Doctrine\DBAL\Exception\DriverException]
> SQLSTATE[22021]: Character not in repertoire

zbateson/mail-mime-parser's [`$message->getTextContent()`](https://github.com/zbateson/mail-mime-parser/blob/master/src/Message.php#L234) is returning:
```
für möglich häufig
```

I fixed it with this simple check:
```php
if (mb_check_encoding($parser->getMessageBody('text'), 'UTF-8'))
{
    $text = $parser->getMessageBody('text');
}
else
{
    $text = utf8_encode($parser->getMessageBody('text'));
}
```

So I'm suggesting that you include this right into the decoding process for the reason: If the result just is not UTF-8 (as expected), instead of crashing, try to sanitize it :-)  
I guess the right place would be `Parser::decodeContentTransfer()`. I'd be happy to add a PR, but I see quite some difference between master and the latest release 6.0.0, so I don't know where to start ;-)

**Comment by eXorus** [comment]
Thanks for the clear report. 

So the fix will be to use utf8_encode if the text is not in UTF8 to sanitize but the function utf8_encode() is only available to encode an ISO-8859-1 string to UTF-8.

https://www.php.net/manual/en/function.utf8-encode.php
> Many web pages marked as using the ISO-8859-1 character encoding actually use the similar Windows-1252 encoding, and web browsers will interpret ISO-8859-1 web pages as Windows-1252. Windows-1252 features additional printable characters, such as the Euro sign (€) and curly quotes (“ ”), instead of certain ISO-8859-1 control characters. This function will not convert such Windows-1252 characters correctly. Use a different function if Windows-1252 conversion is required. 


> I guess the right place would be Parser::decodeContentTransfer(). I'd be happy to add a PR, but I see quite some difference between master and the latest release 6.0.0, so I don't know where to start ;-)

It's more related to Charset than ContentTransfer because your email already have a the value "quoted-printable" for the content transfer.
You should start the PR with master.

You can try and we will see if all the tests passed.

**Comment by eXorus** [comment]
Thanks for the report.

The issue was about `decodeCharset` in `Charset.php`, the expected output should always be an UTF8 string.

And for ASCII string it was returned as it is.

It's now encode to UTF8.

**Comment by scofield-ua** [comment]
@eXorus 

I think there is a bug in here.

Here is contents of email we received:
```
Return-Path: <robot@example.org>
Received: from example.org (example.org [xxx.xxx.xx])
 by inbound-smtp.us-east-1.amazonaws.com with SMTP id m0h70o336a5mv7k4rbenj0dg3juroo60rc399ag1
 for email@example.org;
 Wed, 24 Nov 2021 19:27:44 +0000 (UTC)
X-SES-Spam-Verdict: PASS
X-SES-Virus-Verdict: PASS
Received-SPF: none (spfCheck: xxx.xxx.xx is neither permitted nor denied by domain of example.org) client-ip=xxx.xxx.xx; envelope-from=robot@example.org; helo=example.org;
Authentication-Results: amazonses.com;
 spf=none (spfCheck: xxx.xxx.xx is neither permitted nor denied by domain of example.org) client-ip=xxx.xxx.xx; envelope-from=robot@example.org; helo=example.org;
 dmarc=none header.from=example.org;
Subject: Добро пожаловать на сайт example.org
To: email@example.org
Reply-to: robot@example.org
From: robot@example.org
Message-ID: <1b0ade9e53d92260e2a47762169a17a5@example.org>
MIME-Version: 1.0
Content-type: text/plain; charset=windows-1251
Content-transfer-encoding: 8bit
Date: Wed, 24 Nov 2021 22:27:43 +0300
X-Priority: 0
X-MSMail-Priority: Normal
X-Mailer: Microsoft Office Outlook, Build 11.0.5510
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2800.1441
X-Sender: robot@example.org

Добро пожаловать на сайт example.org
```

Expected result:
```
Добро пожаловать на сайт example.org
```

Actual result:
```
Р”РѕР±СЂРѕ РїРѕР¶Р°Р»РѕРІР°С‚СЊ РЅР° СЃР°Р№С‚ example.org
```

I made some digging and I think the problem is [$this->charset->decodeCharset function](https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/9d09a017f3f103fec8456211a4a538b80e0eca0d/src/Parser.php#L492).

I had to use `mb_convert_encoding` for this specific email:

```
$textVersion = $this->parser->getMessageBody('text');
$textVersion = mb_convert_encoding($textVersion, 'windows-1251', 'utf-8');
```

**Comment by eXorus** [comment]
What version do you have because with the version 7.0.0 I have the expected result.
With master also.

Or maybe it's related to a php configuration about charset in your environment.

**Comment by scofield-ua** [comment]
So I tried versions: `^7.0` and `dev-master`. Same problem.

The problem is in [decoded function](https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/361af57c49b60ce0eea0b38d14460c583c7ce7ee/src/Entity.php#L303-L310).

So if I replace it with:
```
public function decoded()
{
    $undecodedBody = $this->parserConfig->getContentTransferEncodingManager()->decodeContentTransfer(
        $this->getBody(),
        $this->getContentTransferEncoding()
    );
    
    return $undecodedBody;
}
```
then everything works as expected. 

Which environment charset settings I can check? Current charset related settings:
```
bash-5.1# php -i | grep charset
default_charset => UTF-8 => UTF-8
mailparse.def_charset => us-ascii => us-ascii
```

**Comment by eXorus** [comment]
I really don't know.
Your email is in `windows-1251` so the code do `mb_convert_encoding($encodedString, 'utf-8', $charset);`
It's here: https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/361af57c49b60ce0eea0b38d14460c583c7ce7ee/src/Charset.php#L338

It should work as expected. I think it's related to your system maybe `mb_list_encodings` doesn't return the same list than us.
