### ISSUE TITLE
Header `Content-Disposition:` in main message leads to body being treated as attachment

### ISSUE THREAD

**Issue by ThomasLandauer** [php-mime-mail-parser/php-mime-mail-parser#337]
I have this:
```
From: <foo@example.com>
Date: Fri, 22 Dec 2017 06:34:08 +0100
MIME-Version: 1.0
Content-type: multipart/mixed; Boundary="0__=12345"
Content-Disposition: inline

--0__=12345
Content-type: text/plain; charset=UTF-8

foobar

--0__=12345
Content-type: image/jpeg; name="foobar.jpg"
Content-Disposition: attachment; filename="foobar.jpg"
Content-transfer-encoding: base64

--0__=12345--
```
...and `count($parser->getAttachments())` gives me `2`, with the *entire* message being the first "attachment".

However, it's just a `text/plain` body with one attachment - this is also what [zbateson/mail-mime-parser](https://github.com/zbateson/mail-mime-parser)'s `$message->getAllAttachmentParts()` returns.

When I delete the `Content-Disposition: inline` header, everything is fine (i.e. just 1 attachment). So your attachment detection mechanism probably relies too much on a `Content-Disposition:` header.

[RFC 2183](https://tools.ietf.org/html/rfc2183#section-2.10) says:

> It is permissible to use Content-Disposition on the main body of an [RFC 822] message.

This applies to your latest release (v6.0.0) - I tried to find the relevant code part in `master`, but there are too many changes since v6...

**Comment by eXorus** [comment]
@ThomasLandauer 

Yes it was one of the big difference between php-mime-mail-parser and zbateson parser.
php-mime-mail-parser get all the attachments:
- root attachments
- nested attachments
- inline attachments
by default.
And it's possible to filter these attachments with others functions.

I agree that it's not what you expect as a user by default.
That's why it has been totally rework on master.

You can see the result on the next version, it's already fixed.
But I can't apply the fix on 6.0 because it will be a breaking changes.

**Comment by eXorus** [comment]
https://github.com/php-mime-mail-parser/php-mime-mail-parser/pull/338

**Comment by ThomasLandauer** [comment]
OK, I see, thanks, so I'm closing this for now :-)
