### ISSUE TITLE
url does not convert into active link in some mails

### ISSUE THREAD

**Issue by husaindevelop** [php-mime-mail-parser/php-mime-mail-parser#364]
**Describe the bug**
Few mails, especially simple verification mails url do not get converted into active links.

**To Reproduce**
```
require_once __DIR__.'/appln_enterprise/test/vendor/autoload.php';
$parser = new PhpMimeMailParser\Parser();
 $parser->setText(file_get_contents($path));
  //$parser->setPath($path);
 $text = $parser->getMessageBody('html');
 $htmlEmbedded = $parser->getMessageBody('htmlEmbedded');
```

**Expected behavior**
It should convert the url into a active link. As you can see in the screenshot, the url below the text: "Please confirm that this email address is correct by clicking the link below" has not converted into a active link. 

**Screenshots**
![screencapture-mbracecloud-2021-03-28-09_48_37](https://user-images.githubusercontent.com/62126860/112742282-dbd03600-8faa-11eb-93cb-66fe8da47021.png)

**Version (please complete the following information):**
 - Version of mailparse: [e.g. 3.1.1]
 - Version of PHP [e.g. PHP 7.4]
 7.4
 - Version of php-mime-mail-parser [e.g. 6.1]
 Latest one

**Additional context**

**Comment by eXorus** [comment]
Hello,

Thanks for the report, but the HTML version of the email doesn't contain any link so it's normal.

https://mailo.xyz/emails/41b4b887-7745-4abc-81c9-e40a864e9fa8

Because I guess it's not a link, if the raw html email is like this
```
Please conf=
irm that this email address is correct by clicking on the link below: <=
br /><br />https://www.finextra.com/about/newsletterconfirmation.aspx?t=
oken=3D079dd8dd-66a8-4874-b457-8c95aec605aa<br /><br />

```

After you can transform all the links in a real link in your webmail but the purpose of php-mime-mail-parser is only to parse the email like it is.
