### ISSUE TITLE
getMessageBody does not strip attachments

### ISSUE THREAD

**Issue by lcdservices** [php-mime-mail-parser/php-mime-mail-parser#382]
**Describe the bug**
I have email content with attachments. getAttachments() and saveAttachments() work fine. But I expect `$parser->getMessageBody('html');` to return the HTML without the attachments, but it does not -- the attachment coding is included in the html response.

**To Reproduce**
Parse an email with embedded attachments. Use `getMessageBody('html')` to retrieve the HTML. Examine the response.

**Expected behavior**
`getMessageBody('html')` returns clean html content.

**Comment by eXorus** [comment]
What do you mean by clean html content?
- it could be remove the html
- it could be let the html like it is (actual result)
- it could be replace by something to show there is an image here for example

I think it's out of my scope to decide.

**Comment by lcdservices** [comment]
I expect `getMessageBody('html')` to return *only*  the HTML for the actual message body -- extracting embedded attachments. The assumption is that if `getMessageBody('htmlEmbedded')` is including embedded content, then `getMessageBody('html')` does not include it.

What I'm finding is that the embedded attachment code is included in what is returned by `getMessageBody('html')`. I don't think the email is malformed. As noted above, `getAttachments()` and `saveAttachments()` will return and save, respectively, the embedded attachments. They simply aren't stripped when seeking to just get the message body.

**Comment by eXorus** [comment]
getMessageBody('html') will return:
`here is my image: <img src="cid:img1">`
In reality it will not display the image because cid:img1 is nothing.

getMessageBody('htmlEmbedded')
`here is my image: <img src="data:798f976a583">`
In reality it will display the image because the image is embedded in base64 in the HTML.


If I understand correctly you would like to have, but I don't think it's my job to do this kind of work.
getMessageBody('html') will return:
`here is my image: `

Thanks for your feedback! If I haven't understood your requirements correctly, feel free to reopen the issue so we can further clarify.
