### ISSUE TITLE
How to construct an email with content from `$htmlEmbedded`

### ISSUE THREAD

**Issue by ramzlab000** [php-mime-mail-parser/php-mime-mail-parser#442]
Hello

I am trying to construct an email which essentially sends the email content to a different recipent. But the embedded images are displayed in gibberish when `$htmlEmbedded` is under and nothing is displayed when`$html` is used as body of the email using PHPMailer.

Any pointers would be hightly appreciated?

Also, do you have a documentation link somewhere?

Thanks,

**Comment by eXorus** [comment]
What do you mean by 'weird'? Do you have an example?

When using $parser->getMessageBody('htmlEmbedded');, the email should be perfect as the images are replaced with base64-encoded images.

However, sending the email directly in htmlEmbedded doesn't seem like a good idea. It would be better to create a multipart email with the images as inline attachments.

For forwarding an email, I would recommend doing it at the email server level rather than decoding an email, re-encoding it, and sending it again. However, this will depend on the specific use case.

**Comment by ramzlab000** [comment]
Thanks for the response. 

I could use the `$parser->getMessageBody('html');` along with `$attachment->getContentID();` and `$attachment->getContentDisposition()` to construct the email. Just had to dig through the code a bit to understand since there is not documentation of the `$attachment` object.

**Comment by eXorus** [comment]
Yes, I completely understand the challenge of reconstructing an email from a parsed one—it's not an easy task.

If you are not modifying the content of the email, I really recommend opting for a solution at the email server level by configuring a forward or relay. It will be much more efficient and clean.

If you still need to reconstruct the email, then you will have to look into libraries for sending emails, which explain how to construct an email and then "just" reorder all the parsed email elements correctly. Indeed, you would provide the HTML with attached files and see how to do embedded images. For example, in Laravel, it's done like this: [Laravel Inline Attachments](https://laravel.com/docs/11.x/mail#inline-attachments).
