### ISSUE TITLE
Extract body mail without all replies

### ISSUE THREAD

**Issue by george-dragnea** [php-mime-mail-parser/php-mime-mail-parser#68]
There is a way to extract only the body of email without the replies/quotes ?

Thanks

**Comment by noobiwan** [comment]
Replies and quotes **are** part of the body part of the email. It's up to _you_ to parse the body to extract the message you want and ignore the replies and quotes. It involves quite a bit of work because there is no standard, so you will have to account for all different email clients and different quotes styles etc.
