### ISSUE TITLE
Error in Parser.php on line 357

### ISSUE THREAD

**Issue by icolombi** [php-mime-mail-parser/php-mime-mail-parser#94]
Hi,

sometimes I get this error, I think caused by attachment that contains "strange" characters:
```
Warning: fopen(/opt/attachments/Convegno ABI “Unione Bancaria e Basilea 3” - 21/22 giugno 2016 - 3 SETTIMANE AL VIA!): failed to open stream: No such file or directory in /opt/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php on line 350

Fatal error: Uncaught Exception: Could not write attachments. Your directory may be unwritable by PHP. in /opt/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php:357
Stack trace:
#0 /opt/bounce.php(151): PhpMimeMailParser\Parser->saveAttachments('/opt/...')
#1 {main}
  thrown in /opt/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php on line 357
```
the directory permission is ok, I can parse other messages with attachments without problems.

**Comment by eXorus** [comment]
Hello,

Which version do you used (fopen is not in line 350 anymore) ?

Are you on Windows or Linux server ?

Are you sure that this file doesn't exist before ? 2 mails with the same attachments.

It's not a good practice I think to use {Convegno ABI “Unione Bancaria e Basilea 3” - 21/22 giugno 2016 - 3 SETTIMANE AL VIA!} as a name of a file. If I create a file name like that on my ubuntu desktop it is refused because / is forbidden characters.

**Comment by icolombi** [comment]
Hello,

thanks for the feedback. It's version 2.30 and it runs on CentOS 6.7 with php 7.0.6.

No the file was not present before.

I'm aware that the file name may be the prolem, but since I use the parser to process bounces I have no control about the email content.

**Comment by eXorus** [comment]
It's related to #63 but nobody want to finish the PR :)
It will be great to do that
